stages:
  - test
  - build
  - deploy

test-skill-api:
  stage: test
  image: golang:latest
  script:
    - cd api
    - go install
    - make test

test-skill-consumer:
  stage: test
  image: golang:latest
  script:
    - cd consumer
    - go install
    - make test