stages:
  - test
  - build
  - deploy

test-skill-api:
  stage: test
  image: golang:latest
  script:
    - cd api
    - go install
    - make test

test-skill-consumer:
  stage: test
  image: golang:latest
  script:
    - cd consumer
    - go install
    - make test

build-skill-api:
  stage: build
  needs:
    - job: test-skill-api
  image: docker:latest
  # when: manual
  services:
    - docker:dind
  script:
    - ./build-docker-skill-api.sh

build-skill-consumer:
  stage: build
  needs:
    - job: test-skill-consumer
  image: docker:latest
  # when: manual
  services:
    - docker:dind
  script:
    - ./build-docker-skill-consumer.sh